### ISSUE TITLE
MPS Follow Up: intermitent startup failure

### ISSUE THREAD

**Issue by Gnuxie** [the-draupnir-project/Draupnir#333]
```
Wed, 10 Apr 2024 20:34:58 GMT [ERROR] [ActionException] ActionException Unknown 8b14aec4-8f19-473f-b450-1fafe48adc4a M_UNKNOWN: Failed to fetch alias undefined
Failed to setup mjolnir from the config /data/storage: Error: Unable to create Draupnir: Could not load MjolnirPolicyRoomsConfig
/mjolnir/DraupnirBotMode.js:73
        throw new Error(`Unable to create Draupnir: ${error.message}`);
        ^
Error: Unable to create Draupnir: Could not load MjolnirPolicyRoomsConfig
    at makeDraupnirBotModeFromConfig (/mjolnir/DraupnirBotMode.js:73:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /mjolnir/index.js:100:15
```

**Comment by Gnuxie** [comment]
```
    const watchedListsResult = await store.requestAccountData();
    if (isError(watchedListsResult)) {
      return watchedListsResult;
    }
    const references = watchedListsResult.ok?.references ?? [];
    const issuers = await Promise.all(
      references.map(async (room) => {
        const resolvedRoomResult = await roomJoiner.resolveRoom(room);
        if (isError(resolvedRoomResult)) {
          return resolvedRoomResult;
        }
        return policyRoomManager.getPolicyRoomRevisionIssuer(
          resolvedRoomResult.ok
        );
      })
    )
    ```
    
    Somehow one of the references is undefined

**Comment by Gnuxie** [comment]
This seems to have been either fixed, and if it hasn't, it's also covered by safe mode
