### ISSUE TITLE
Figure out how to avoid `present` conflicts by using a mirror to call a presentation method.

### ISSUE THREAD

**Issue by Gnuxie** [the-draupnir-project/Draupnir#403]
```
ActionException ActionException Unknown fb941277-4f62-40d2-88cc-ff02cc6018df Unknown Unexpected Error TypeError: presentationTypeof: There are multiple candidates for the presentation [object Object]: ["MatrixRoomReference","MatrixRoomID"]
    at presentationTypeOf (/home/user/element/mjolnir/src/commands/interface-manager/ParameterParsing.ts:118:15)
    at ensureChild (/home/user/element/mjolnir/src/commands/interface-manager/JSXFactory.ts:34:56)
    at Array.forEach (<anonymous>)
    at JSXFactory (/home/user/element/mjolnir/src/commands/interface-manager/JSXFactory.ts:43:17)
    at /home/user/element/mjolnir/src/commands/interface-manager/MatrixPromptForAccept.tsx:182:28
    at Array.map (<anonymous>)
    at Object.promptSuggestions (/home/user/element/mjolnir/src/commands/interface-manager/MatrixPromptForAccept.tsx:181:30)
    at MatrixInterfaceAdaptor.invoke (/home/user/element/mjolnir/src/commands/interface-manager/MatrixInterfaceAdaptor.ts:99:45)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handleCommand (/home/user/element/mjolnir/src/commands/CommandHandler.ts:89:20)
```

**Comment by Gnuxie** [comment]
This mirror now exists.
