### ISSUE TITLE
`FirstMessageIsImageProtection` is broken in beta

### ISSUE THREAD

**Issue by Gnuxie** [the-draupnir-project/Draupnir#442]
```
modbot32-1  | Failed to setup mjolnir from the config /data/storage: TypeError: Cannot find a renderer for the capability provider named StandardEventConsequences
modbot32-1  | /node_modules/matrix-protection-suite/dist/Protection/Capability/CapabilityRenderer.js:37
modbot32-1  |         throw new TypeError(`Cannot find a renderer for the capability provider named ${capabilityProviderDescription.name}`);
modbot32-1  |               ^
modbot32-1  |
modbot32-1  | TypeError: Cannot find a renderer for the capability provider named StandardEventConsequences
modbot32-1  |     at wrapCapabilityProviderInRenderer (/node_modules/matrix-protection-suite/dist/Protection/Capability/CapabilityRenderer.js:37:15)
modbot32-1  |     at initializeCapabilitySet (/node_modules/matrix-protection-suite/dist/Protection/Capability/CapabilitySet.js:12:79)
modbot32-1  |     at StandardProtectionsManager.addProtectionSync (/node_modules/matrix-protection-suite/dist/Protection/ProtectionsManager/FakeProtectionsManager.js:22:74)
modbot32-1  |     at StandardProtectionsManager.startProtection (/node_modules/matrix-protection-suite/dist/Protection/ProtectionsManager/StandardProtectionsManager.js:41:40)
modbot32-1  |     at StandardProtectionsManager.loadProtections (/node_modules/matrix-protection-suite/dist/Protection/ProtectionsManager/StandardProtectionsManager.js:57:38)
modbot32-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
modbot32-1  |     at async Draupnir.makeDraupnirBot (/mjolnir/Draupnir.js:126:28)
modbot32-1  |     at async DraupnirFactory.makeDraupnir (/mjolnir/draupnirfactory/DraupnirFactory.js:35:16)
modbot32-1  |     at async makeDraupnirBotModeFromConfig (/mjolnir/DraupnirBotMode.js:70:22)
modbot32-1  |     at async /mjolnir/index.js:100:15
modbot32-1  |
modbot32-1  | Node.js v20.14.0
modbot32-1 exited with code 0
```

context: https://matrix.to/#/%23draupnir%3Amatrix.org/%24Od5SJ0BI9QVhiPA6bdmC5sn3Ib7Hj3bsBxCCn20Rx6M?via=matrix.org&via=envs.net&via=ubuntu.com

**Comment by Gnuxie** [comment]
This is no longer true
