### ISSUE TITLE
Draupnir fails unexpectedly if matrix-bot-sdk decides server hasn't responded to`/join`.

### ISSUE THREAD

**Issue by TheArcaneBrony** [the-draupnir-project/Draupnir#561]
Draupnir consistently seems to fail to start.
Version: 86b7a51992b0ffbeae74500bcdcbb65706fe636d

```
Sep 16 03:04:02 Rory-nginx draupnir[387004]: Mon, 16 Sep 2024 03:04:02 GMT [ERROR] [ActionException] ActionException Unknown 00e73c5d-7d94-4df8-8f2d-561038c787ab undefined: undefined undefined
Sep 16 03:04:02 Rory-nginx draupnir[387004]: Failed to setup mjolnir from the config /var/lib/draupnir: TypeError: ActionException: 00e73c5d-7d94-4df8-8f2d-561038c787ab
Sep 16 03:04:02 Rory-nginx draupnir[387004]: Unable to join and add configured protected room https://matrix.to/#/!fcnmIxfgNvHewKXXDj%3Aopensuse.org
Sep 16 03:04:02 Rory-nginx draupnir[387004]: elaborated from: Unable to create Draupnir
Sep 16 03:04:02 Rory-nginx draupnir[387004]: caused by: undefined: undefined
Sep 16 03:04:02 Rory-nginx draupnir[387004]: from error: undefined
Sep 16 03:04:02 Rory-nginx draupnir[387004]: /nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@gnuxie/typescript-result/dist/Result.js:132
Sep 16 03:04:02 Rory-nginx draupnir[387004]:         return new TypeError(this.toReadableString());
Sep 16 03:04:02 Rory-nginx draupnir[387004]:                ^
Sep 16 03:04:02 Rory-nginx draupnir[387004]: TypeError: ActionException: 00e73c5d-7d94-4df8-8f2d-561038c787ab
Sep 16 03:04:02 Rory-nginx draupnir[387004]: Unable to join and add configured protected room https://matrix.to/#/someroom:xyz.xyz
Sep 16 03:04:02 Rory-nginx draupnir[387004]: elaborated from: Unable to create Draupnir
Sep 16 03:04:02 Rory-nginx draupnir[387004]: caused by: undefined: undefined
Sep 16 03:04:02 Rory-nginx draupnir[387004]: from error: undefined
Sep 16 03:04:02 Rory-nginx draupnir[387004]:     at MatrixException.toExpectError (/nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@gnuxie/typescript-result/dist/Result.js:132:16)
Sep 16 03:04:02 Rory-nginx draupnir[387004]:     at ExpectError (/nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@gnuxie/typescript-result/dist/Result.js:71:28)
Sep 16 03:04:02 Rory-nginx draupnir[387004]:     at Object.expect (/nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@gnuxie/typescript-result/dist/Result.js:76:12)
Sep 16 03:04:02 Rory-nginx draupnir[387004]:     at makeDraupnirBotModeFromConfig (/nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/deps/draupnir/lib/DraupnirBotMode.js:60:21)
Sep 16 03:04:02 Rory-nginx draupnir[387004]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Sep 16 03:04:02 Rory-nginx draupnir[387004]:     at async /nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/deps/draupnir/lib/index.js:87:15
Sep 16 03:04:02 Rory-nginx draupnir[387004]: Node.js v20.14.0
Sep 16 03:04:02 Rory-nginx systemd[1]: draupnir.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by TheArcaneBrony** [comment]
Update: it has now started, not sure what caused this.

**Comment by Gnuxie** [comment]
>Unable to join and add configured protected room https://matrix.to/#/someroom:xyz.xyz

You had some dummy values in the config file for `protectedRooms`

**Comment by TheArcaneBrony** [comment]
Only just caught your comment, iirc we investigated this out of bounds and found that some dummy values was not the case, as `protectedRooms` isn't configured at all. Rather, as mentioned in multiple commits before this message, the issue was caused by the server not responding to /join under specific circumstances.

Just thought i'd follow up with public context.

**Comment by Gnuxie** [comment]
Fixed in develop, and this scenario will be pretty well covered by safe mode (specifically which protected room is causing issues will be explicitly communicated under the current plan)

**Comment by TheArcaneBrony** [comment]
Oh, cool, thanks gnuxie!
