### ISSUE TITLE
Draupnir fails to start if it was banned from a protected room

### ISSUE THREAD

**Issue by TheArcaneBrony** [the-draupnir-project/Draupnir#580]
I might be out of date and this may have been fixed together with #561 

Logs:
```
Sep 26 16:41:23 Rory-nginx draupnir[333579]: WARNING: No configurations found in configuration directory:/var/lib/private/draupnir/config
Sep 26 16:41:23 Rory-nginx draupnir[333579]: WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
Sep 26 16:41:23 Rory-nginx draupnir[333579]: Thu, 26 Sep 2024 16:41:23 GMT [INFO] [index] Starting bot...
Sep 26 16:41:31 Rory-nginx draupnir[333579]: Thu, 26 Sep 2024 16:41:31 GMT [ERROR] [ActionException] ActionException Unknown 445f93e6-3a7b-4374-9492-06593b1710b0 M_BAD_STATE: Cannot join user who was banned undefined
Sep 26 16:41:31 Rory-nginx draupnir[333579]: Failed to setup mjolnir from the config /var/lib/draupnir: TypeError: ActionException: 445f93e6-3a7b-4374-9492-06593b1710b0
Sep 26 16:41:31 Rory-nginx draupnir[333579]: Unable to join and add configured protected room https://matrix.to/#/!aYqHMneYZdQrqyuYYB%3Aunix.dog
Sep 26 16:41:31 Rory-nginx draupnir[333579]: elaborated from: Unable to create Draupnir
Sep 26 16:41:31 Rory-nginx draupnir[333579]: caused by: M_BAD_STATE: Cannot join user who was banned
Sep 26 16:41:31 Rory-nginx draupnir[333579]: from error: undefined
Sep 26 16:41:31 Rory-nginx draupnir[333579]: /nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@gnuxie/typescript-result/dist/Result.js:132
Sep 26 16:41:31 Rory-nginx draupnir[333579]:         return new TypeError(this.toReadableString());
Sep 26 16:41:31 Rory-nginx draupnir[333579]:                ^
Sep 26 16:41:31 Rory-nginx draupnir[333579]: TypeError: ActionException: 445f93e6-3a7b-4374-9492-06593b1710b0
Sep 26 16:41:31 Rory-nginx draupnir[333579]: Unable to join and add configured protected room https://matrix.to/#/!aYqHMneYZdQrqyuYYB%3Aunix.dog
Sep 26 16:41:31 Rory-nginx draupnir[333579]: elaborated from: Unable to create Draupnir
Sep 26 16:41:31 Rory-nginx draupnir[333579]: caused by: M_BAD_STATE: Cannot join user who was banned
Sep 26 16:41:31 Rory-nginx draupnir[333579]: from error: undefined
Sep 26 16:41:31 Rory-nginx draupnir[333579]:     at MatrixException.toExpectError (/nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@gnuxie/typescript-result/dist/Result.js:132:16)
Sep 26 16:41:31 Rory-nginx draupnir[333579]:     at ExpectError (/nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@gnuxie/typescript-result/dist/Result.js:71:28)
Sep 26 16:41:31 Rory-nginx draupnir[333579]:     at Object.expect (/nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@gnuxie/typescript-result/dist/Result.js:76:12)
Sep 26 16:41:31 Rory-nginx draupnir[333579]:     at makeDraupnirBotModeFromConfig (/nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/deps/draupnir/lib/DraupnirBotMode.js:60:21)
Sep 26 16:41:31 Rory-nginx draupnir[333579]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Sep 26 16:41:31 Rory-nginx draupnir[333579]:     at async /nix/store/hy8mb336c7jnv2403zkh364cdvcrd6qr-draupnir-2.0.0-beta.6/share/draupnir/deps/draupnir/lib/index.js:87:15
Sep 26 16:41:31 Rory-nginx draupnir[333579]: Node.js v20.14.0
Sep 26 16:41:31 Rory-nginx systemd[1]: draupnir.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by Gnuxie** [comment]
https://github.com/the-draupnir-project/Draupnir/issues/547#issuecomment-2631589642
