### ISSUE TITLE
TypeError: We should always be able to get the base command table

### ISSUE THREAD

**Issue by TheArcaneBrony** [the-draupnir-project/Draupnir#620]
Draupnir version: 2.0.0-beta.6

Genuinely no clue what happened here (prior logs are irrelevant):

```
Oct 31 17:43:01 draupnir-fedora draupnir[236]: Thu, 31 Oct 2024 17:43:01 GMT [INFO] [MPSInterfaceAdaptor] Command being processed for @emma:rory.gay: draupnir has some performance issues when you throw it at nearly 100 large rooms on a single process --P
Oct 31 17:43:01 draupnir-fedora draupnir[236]: /nix/store/dbvkfc5jh9cqv46s3cr3rdv24bi0mn7s-draupnir-2.0.0-beta.6/share/draupnir/deps/draupnir/lib/commands/Help.js:36
Oct 31 17:43:01 draupnir-fedora draupnir[236]:             throw new TypeError(`We should always be able to get the base command table`);
Oct 31 17:43:01 draupnir-fedora draupnir[236]:                   ^
Oct 31 17:43:01 draupnir-fedora draupnir[236]: TypeError: We should always be able to get the base command table
Oct 31 17:43:01 draupnir-fedora draupnir[236]:     at Object.JSXRenderer (/nix/store/dbvkfc5jh9cqv46s3cr3rdv24bi0mn7s-draupnir-2.0.0-beta.6/share/draupnir/deps/draupnir/lib/commands/Help.js:36:19)
Oct 31 17:43:01 draupnir-fedora draupnir[236]:     at StandardMatrixInterfaceAdaptor.maybeRunJSXRenderer (/nix/store/dbvkfc5jh9cqv46s3cr3rdv24bi0mn7s-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@the-draupnir-project/interface-manager/dist/MatrixInterfaceAdaptor/MatrixInterfaceAdaptor.js:59:39)
Oct 31 17:43:01 draupnir-fedora draupnir[236]:     at StandardMatrixInterfaceAdaptor.runRenderersOnCommandResult (/nix/store/dbvkfc5jh9cqv46s3cr3rdv24bi0mn7s-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@the-draupnir-project/interface-manager/dist/MatrixInterfaceAdaptor/MatrixInterfaceAdaptor.js:39:18)
Oct 31 17:43:01 draupnir-fedora draupnir[236]:     at StandardMatrixInterfaceAdaptor.parseAndInvoke (/nix/store/dbvkfc5jh9cqv46s3cr3rdv24bi0mn7s-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@the-draupnir-project/interface-manager/dist/MatrixInterfaceAdaptor/MatrixInterfaceAdaptor.js:119:36)
Oct 31 17:43:01 draupnir-fedora draupnir[236]:     at StandardMatrixInterfaceCommandDispatcher.handleCommandMessageEvent (/nix/store/dbvkfc5jh9cqv46s3cr3rdv24bi0mn7s-draupnir-2.0.0-beta.6/share/draupnir/node_modules/@the-draupnir-project/interface-manager/dist/MatrixInterfaceAdaptor/MatrixInterfaceCommandDispatcher.js:36:36)
Oct 31 17:43:01 draupnir-fedora draupnir[236]:     at Draupnir.managementRoomMessageListener (/nix/store/dbvkfc5jh9cqv46s3cr3rdv24bi0mn7s-draupnir-2.0.0-beta.6/share/draupnir/deps/draupnir/lib/Draupnir.js:169:36)
Oct 31 17:43:01 draupnir-fedora draupnir[236]:     at Draupnir.handleTimelineEvent (/nix/store/dbvkfc5jh9cqv46s3cr3rdv24bi0mn7s-draupnir-2.0.0-beta.6/share/draupnir/deps/draupnir/lib/Draupnir.js:141:14)
Oct 31 17:43:01 draupnir-fedora draupnir[236]:     at StandardClientRooms.emit (node:events:519:28)
Oct 31 17:43:01 draupnir-fedora draupnir[236]:     at StandardClientRooms.emit (node:domain:488:12)
Oct 31 17:43:01 draupnir-fedora draupnir[236]:     at StandardClientRooms.handleTimelineEvent (/nix/store/dbvkfc5jh9cqv46s3cr3rdv24bi0mn7s-draupnir-2.0.0-beta.6/share/draupnir/node_modules/matrix-protection-suite/dist/ClientManagement/StandardClientRooms.js:96:18)
Oct 31 17:43:01 draupnir-fedora draupnir[236]: Node.js v20.14.0
Oct 31 17:43:01 draupnir-fedora systemd[1]: draupnir.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by TheArcaneBrony** [comment]
Seems to be reproducible if you send this in the management room (minimal message that reproduces this behavior):
`draupnir :p`

**Comment by Gnuxie** [comment]
Hi this is fixed in beta.8 if you can upgrade

**Comment by TheArcaneBrony** [comment]
Alright, will see if i can, thanks!

**Comment by TheArcaneBrony** [comment]
well, i guess it didnt crash this time, did respond twice though :)
![image](https://github.com/user-attachments/assets/ebf32b79-c5d2-4d81-aa1c-3ba9e45d7728)
