### ISSUE TITLE
Unable to decode schema from value

### ISSUE THREAD

**Issue by timedoutuk** [the-draupnir-project/Draupnir#630]
I run two draupnir instances at the moment. Both are running v2.0.0-beta.8 via docker, however, one of them is brand new, and cannot subscribe to policy lists.

Running `!draupnir watch <room>` makes the bot join the room, and then it will spit out `Unable to decode schema from value`.

Both times, I get a traceback similar to below:

```
Fri, 29 Nov 2024 16:30:49 GMT [ERROR] [ActionException] ActionException Unknown 72f1f0ed-b22b-4454-92d8-8fbe7376b546 Unable to decode schema from value TransformEncodeCheckError: The encoded value does not match the expected schema
    at TypeCheck.Encode (/node_modules/@sinclair/typebox/build/cjs/compiler/compiler.js:57:19)
    at /node_modules/matrix-protection-suite/dist/Interface/Value.js:55:60
    at Value.resultify (/node_modules/matrix-protection-suite/dist/Interface/Value.js:64:37)
    at Value.Encode (/node_modules/matrix-protection-suite/dist/Interface/Value.js:55:21)
    at StandardPersistentConfigData.saveConfig (/node_modules/matrix-protection-suite/dist/Config/PersistentConfigData.js:27:44)
    at MjolnirPolicyRoomsConfig.watchList (/node_modules/matrix-protection-suite/dist/Protection/PolicyListConfig/MjolnirPolicyRoomsConfig.js:65:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.executor (/draupnir/commands/WatchUnwatchCommand.js:27:16)
    at async StandardCommandInvoker.invoke (/node_modules/@the-draupnir-project/interface-manager/dist/Adaptor/StandardCommandInvoker.js:24:20)
    at async StandardMatrixInterfaceAdaptor.invoke (/node_modules/@the-draupnir-project/interface-manager/dist/MatrixInterfaceAdaptor/MatrixInterfaceAdaptor.js:27:31) {
  schema: {
    title: 'PolicyRoomsConfig',
    type: 'object',
    properties: { references: [Object] },
    required: [ 'references' ],
    [Symbol(TypeBox.Kind)]: 'Object'
  },
  value: { references: [ [MatrixRoomID], [MatrixRoomID], [MatrixRoomID] ] },
  error: {
    type: 54,
    schema: {
      type: 'string',
      [Symbol(TypeBox.Kind)]: 'String',
      [Symbol(TypeBox.Transform)]: [Object]
    },
    path: '/references/0',
    value: MatrixRoomID {
      reference: '!WuBtumawCeOGEieRrp:matrix.org',
      viaServers: []
    },
    message: 'Expected string'
  }
}
```

This is an issue as the bot fails to subscribe to policy lists.
To rule out the issue being the sheer size of these banlist rooms, I made it join my own personal one, and got the same error.

**Comment by FSG-Cat** [comment]
This issue seems to be caused by trying to subscribe to the same list twice thats why it was assigned as a Nuisance and Rendering issue. P1 is provisional as it could be a P2.

**Comment by Gnuxie** [comment]
The actual cause of the issue was draupnir responding twice to commands, probably because conduwuit sync responses overlap and send the same event separatly. Apparently this was fixed but i think for now its safe to say the fix is dubious. https://github.com/girlbossceo/conduwuit/issues/606

**Comment by nexy7574** [comment]
I can say that at *least* as of Conduwuit 0.5.0 that the duplicate event bug was fixed, however, I'm fairly sure that the issue is also present in other Conduit forks, so unsure if this is something that should remain open or not
